#!/usr/bin/env bash
#
# Static drift check for the blocks that .github/workflows/ci.yml and
# .github/workflows/e2e.yml must keep identical.
#
# Two blocks are compared today:
#
#   1. the `postgres` service container
#   2. the `Install age` step
#
# Both are ONE decision expressed twice. The postgres services must agree
# on image major, role and password, published port and health probe; the
# age installs must agree on version, checksum, download URL and install
# path. When either pair diverges, the workflow that was not edited keeps
# running against the old shape — and because e2e.yml is
# `workflow_dispatch` only, that divergence surfaces at the moment an
# operator clicks "Run workflow" before a manual deploy, which is the
# worst time to discover it.
#
# The `-h 127.0.0.1` health probe is the live example for (1): a socket
# probe reports healthy during the entrypoint's init-phase temporary
# server, so fixing it in one file and not the other leaves the other
# flaky for a reason unrelated to any diff. For (2) the equivalent is a
# version skew — the E2E binary identity would then be generated by a
# different `age` than the integration suite's — and the install path is
# load-bearing besides: KeyEnvelopeService.ts and storage/binaryIdentity.ts
# resolve the binaries by absolute path, so an install anywhere other than
# /usr/bin fails every wrap/unwrap with ENOENT.
#
# WHY A CHECK AND NOT DEDUPLICATION
#   GitHub Actions offers no include mechanism for a service block.
#   Composite actions have no `services` key — action.yml's top-level
#   keys are name/author/description/inputs/outputs/runs/branding, and
#   `runs.steps` takes only `run` and `uses` steps. Reusable workflows
#   CAN declare services, but the unit of reuse is a whole job: folding
#   `check` (2-way shard matrix, vitest) and `e2e` (Playwright,
#   webServer, MinIO) into one parameterised job to share five lines of
#   service config trades a small duplication for a large conditional.
#   Workflow-level YAML anchors are not supported either.
#
#   The age step COULD live in a composite action — `runs.steps` takes
#   `run` steps. It deliberately does not: Renovate's customManager scans
#   `.github/workflows/**` only, so moving the step would stop the pin
#   being tracked, trading a drift risk this check closes for an
#   update-path gap nothing closes. See .github/renovate.json manager 6
#   and ADR-0027 §Decision.1.
#
# WHAT IT COMPARES
#   Each block with whole-line comments and the block's base indentation
#   removed. Comments are stripped deliberately: each file explains its
#   block in its own terms (vitest's per-fork databases vs Playwright's
#   `ensure-db.mjs`; the age step's `/usr/bin` note is spelled out at
#   length in ci.yml and abbreviated in e2e.yml), and forcing prose to
#   match would be enforcing prose, not configuration. Everything else —
#   image, env, ports, options, version, checksum, install path — must be
#   identical.
#
#   Stripping comments means the `# renovate:` annotation is NOT compared
#   here. Its placement constraint is a different invariant with a
#   different failure mode, guarded by check-renovate-annotations.mjs.
#
# EXIT CODES
#   0  in sync
#   1  drift (the diff is printed)
#   2  structural problem — a file or block is missing, or a file holds
#      more than one of a block, which would make "the block" ambiguous
#      and let this check pass while comparing the wrong pair.
#
# Usage:
#   bash scripts/check-workflow-drift.sh
#
# The two paths are overridable so the self-test
# (scripts/__tests__/check-workflow-drift.test.sh) can stage mutated
# copies without touching the real workflows.

set -euo pipefail

cd "$(dirname "$0")/.."

CI_WORKFLOW="${CI_WORKFLOW:-.github/workflows/ci.yml}"
E2E_WORKFLOW="${E2E_WORKFLOW:-.github/workflows/e2e.yml}"

AGE_STEP_NAME='Install age'

for f in "$CI_WORKFLOW" "$E2E_WORKFLOW"; do
  if [ ! -f "$f" ]; then
    echo "ERROR: $f not found — run from the project root or set CI_WORKFLOW / E2E_WORKFLOW." >&2
    exit 2
  fi
done

# Exactly one of each block per file. Two would mean the extractor
# silently compares the first of each and reports "in sync" about a pair
# nobody asked about.
assert_single() {
  local file="$1" pattern="$2" label="$3" count
  count=$(grep -c "$pattern" "$file" || true)
  if [ "$count" -ne 1 ]; then
    echo "ERROR: $file declares $count '$label' blocks, expected exactly 1." >&2
    echo "       This check compares one block per file; teach it which pair to" >&2
    echo "       compare before adding a second." >&2
    exit 2
  fi
}

for f in "$CI_WORKFLOW" "$E2E_WORKFLOW"; do
  assert_single "$f" '^[[:space:]]*postgres:[[:space:]]*$' 'postgres:'
  assert_single "$f" "^[[:space:]]*-[[:space:]]*name:[[:space:]]*${AGE_STEP_NAME}[[:space:]]*\$" "- name: ${AGE_STEP_NAME}"
done

# Extract `services.postgres` and normalise it for comparison.
#
# awk rather than a YAML parser for the same reason as check-env-drift.sh:
# ubuntu-latest runners ship mawk, and this must run with nothing beyond a
# standard POSIX toolchain. The block is found structurally (a `postgres:`
# key inside a `services:` key), not by line number, so reordering the
# jobs or reindenting a file does not fool it.
extract_pg_service() {
  awk '
    # `services:` at any indent opens the section.
    /^[[:space:]]*services:[[:space:]]*$/ { in_services = 1; next }

    # The `postgres:` key inside it. Its indent is the block boundary:
    # every line belonging to the block is nested deeper.
    in_services && !in_pg && /^[[:space:]]*postgres:[[:space:]]*$/ {
      match($0, /^[[:space:]]*/)
      pg_indent = RLENGTH
      in_pg = 1
      next
    }

    in_pg {
      if ($0 ~ /^[[:space:]]*$/) next            # blank line, no content
      match($0, /^[[:space:]]*/)
      indent = RLENGTH
      if (indent <= pg_indent) { in_pg = 0; next }   # sibling key ends the block
      if ($0 ~ /^[[:space:]]*#/) next            # whole-line comment
      sub(/[[:space:]]+$/, "")                   # trailing whitespace
      lines[++n] = $0
      if (!have_min || indent < min) { min = indent; have_min = 1 }
    }

    # Dedent by the shallowest line so the two blocks compare on relative
    # structure, not on how deep their job happens to sit.
    END { for (i = 1; i <= n; i++) print substr(lines[i], min + 1) }
  ' "$1"
}

# Extract one `- name: <step>` list item and normalise it the same way.
#
# The `-` indent is the boundary: every continuation line of the item is
# nested deeper, and the next `- name:` — or any dedent to a shallower key
# — ends it. The `- name:` line itself is dropped: it is the search key,
# so comparing it would only ever compare the constant passed in.
extract_step() {
  awk -v want="$2" '
    !in_step && $0 ~ /^[[:space:]]*-[[:space:]]*name:[[:space:]]*/ {
      name = $0
      sub(/^[[:space:]]*-[[:space:]]*name:[[:space:]]*/, "", name)
      sub(/[[:space:]]+$/, "", name)
      if (name == want) {
        match($0, /^[[:space:]]*/)
        step_indent = RLENGTH
        in_step = 1
      }
      next
    }

    in_step {
      if ($0 ~ /^[[:space:]]*$/) next            # blank line, no content
      match($0, /^[[:space:]]*/)
      indent = RLENGTH
      if (indent <= step_indent) { in_step = 0; next }   # sibling item ends it
      if ($0 ~ /^[[:space:]]*#/) next            # whole-line comment
      sub(/[[:space:]]+$/, "")                   # trailing whitespace
      lines[++n] = $0
      if (!have_min || indent < min) { min = indent; have_min = 1 }
    }

    END { for (i = 1; i <= n; i++) print substr(lines[i], min + 1) }
  ' "$1"
}

# Compare one extracted pair. Prints the diff and returns 1 on drift, 2
# when either side came back empty (the format changed under us).
compare_blocks() {
  local label="$1" ci_block="$2" e2e_block="$3" guidance="$4"

  if [ -z "$ci_block" ]; then
    echo "ERROR: no $label block extracted from $CI_WORKFLOW — did the format change?" >&2
    return 2
  fi
  if [ -z "$e2e_block" ]; then
    echo "ERROR: no $label block extracted from $E2E_WORKFLOW — did the format change?" >&2
    return 2
  fi

  if [ "$ci_block" != "$e2e_block" ]; then
    echo "ERROR: the $label blocks in $CI_WORKFLOW and $E2E_WORKFLOW have drifted." >&2
    echo "" >&2
    echo "--- $CI_WORKFLOW" >&2
    echo "+++ $E2E_WORKFLOW" >&2
    diff <(printf '%s\n' "$ci_block") <(printf '%s\n' "$e2e_block") >&2 || true
    echo "" >&2
    echo "$guidance" >&2
    echo "" >&2
    echo "If the two genuinely must differ now, that is a design change, not a fixup:" >&2
    echo "say why in a comment in both files and narrow this check to the fields that" >&2
    echo "are still shared — do not delete it." >&2
    return 1
  fi

  echo "OK: $CI_WORKFLOW ↔ $E2E_WORKFLOW $label in sync"
  echo "  compared lines (comments stripped): $(printf '%s\n' "$ci_block" | wc -l)"
  return 0
}

status=0

# `|| rc=$?` rather than a bare call: `set -e` would abort on the first
# drift and hide whether the other block drifted too.
rc=0
compare_blocks \
  "services.postgres" \
  "$(extract_pg_service "$CI_WORKFLOW")" \
  "$(extract_pg_service "$E2E_WORKFLOW")" \
  "Both jobs run integration code against a throwaway Postgres and are meant
to be the same environment. Apply the change to both blocks." || rc=$?
# A structural failure means the file shape changed; reporting the second
# pair on top of that is noise.
if [ "$rc" -eq 2 ]; then exit 2; fi
if [ "$rc" -ne 0 ]; then status=1; fi

rc=0
compare_blocks \
  "step \"$AGE_STEP_NAME\"" \
  "$(extract_step "$CI_WORKFLOW" "$AGE_STEP_NAME")" \
  "$(extract_step "$E2E_WORKFLOW" "$AGE_STEP_NAME")" \
  "Both jobs generate a binary \`age\` identity and must do it with the same
\`age\`. Version, checksum, URL and the /usr/bin install path all have to
match — see ADR-0024 and the script header." || rc=$?
if [ "$rc" -eq 2 ]; then exit 2; fi
if [ "$rc" -ne 0 ]; then status=1; fi

exit "$status"
