/**
 * Emits `src/server/db/migrations/0000_baseline.sql` — the single
 * migration every schema change collapses into (no incremental
 * migrations, ADR-0026). drizzle-kit emits what `schema.ts` declares;
 * what it cannot emit (extensions, seed rows, functions, triggers) is
 * hand-written in `src/server/db/baseline/`:
 *
 *   head/*.sql ──┐
 *   drizzle-kit ─┼─ joined by `--> statement-breakpoint` ─▶ 0000_baseline.sql
 *   tail/*.sql ──┘   (each directory in file-name order)
 *
 * Usage:
 *   npx tsx scripts/generate-baseline.ts           # write in place
 *   npx tsx scripts/generate-baseline.ts --check   # verify only
 *
 * $BASELINE_PATH overrides the target file — used by
 * scripts/__tests__/check-baseline.test.sh to point at a fixture.
 *
 * `meta/_journal.json` is never rewritten. drizzle's migrator applies a
 * migration only when its journal `when` is newer than the ledger's, so
 * a fresh `when` on an unchanged baseline would re-run it against every
 * existing database. Conversely, any change to the output changes its
 * sha256: existing databases then need
 * docs/ops/recover-from-schema-change.md.
 *
 * Exit codes: 0 written / in sync; 1 drift (--check only); 2 toolchain
 * error (drizzle-kit failed, or the target is unreadable in --check).
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DRIZZLE_KIT = path.join(REPO_ROOT, 'node_modules/.bin/drizzle-kit');
const SCHEMA_PATH = 'src/server/db/schema.ts';
const PARTS_DIR = path.join(REPO_ROOT, 'src/server/db/baseline');
const OUT_PATH =
  process.env.BASELINE_PATH ?? path.join(REPO_ROOT, 'src/server/db/migrations/0000_baseline.sql');

const STATEMENT_BREAKPOINT = '\n--> statement-breakpoint\n';
const HEADER = [
  '-- GENERATED by `npm run db:baseline` — do not edit. Sources:',
  `-- ${SCHEMA_PATH} and src/server/db/baseline/{head,tail}/*.sql.`,
  '',
].join('\n');

function generateFromSchema(): string {
  const outDir = mkdtempSync(path.join(tmpdir(), 'baseline-'));
  try {
    // stdout is drizzle-kit's per-table summary; on failure it also
    // carries the reason, so it is surfaced then and only then.
    try {
      execFileSync(
        DRIZZLE_KIT,
        [
          'generate',
          '--dialect',
          'postgresql',
          '--schema',
          SCHEMA_PATH,
          '--out',
          outDir,
          '--name',
          'baseline',
        ],
        { cwd: REPO_ROOT, stdio: ['ignore', 'pipe', 'inherit'] },
      );
    } catch (err) {
      const stdout = (err as { stdout?: Buffer }).stdout?.toString() ?? '';
      throw new Error(`drizzle-kit generate failed:\n${stdout}`, { cause: err });
    }
    return readFileSync(path.join(outDir, '0000_baseline.sql'), 'utf8');
  } finally {
    rmSync(outDir, { recursive: true, force: true });
  }
}

function readParts(dir: 'head' | 'tail'): string[] {
  const partsDir = path.join(PARTS_DIR, dir);
  return readdirSync(partsDir)
    .filter((name) => name.endsWith('.sql'))
    .sort()
    .map((name) => readFileSync(path.join(partsDir, name), 'utf8'));
}

function buildBaseline(): string {
  const parts = [...readParts('head'), generateFromSchema(), ...readParts('tail')];
  return HEADER + parts.map((part) => part.trimEnd()).join(STATEMENT_BREAKPOINT) + '\n';
}

function readTarget(): string | null {
  try {
    return readFileSync(OUT_PATH, 'utf8');
  } catch {
    return null;
  }
}

const checkOnly = process.argv.includes('--check');
const current = readTarget();
if (checkOnly && current === null) {
  console.error(`ERROR: cannot read ${OUT_PATH}`);
  process.exit(2);
}

let expected: string;
try {
  expected = buildBaseline();
} catch (err) {
  console.error('ERROR: failed to build the baseline:', err);
  process.exit(2);
}

if (checkOnly) {
  if (current === expected) {
    console.log(`OK: ${OUT_PATH} is in sync with schema.ts and src/server/db/baseline/.`);
    process.exit(0);
  }
  console.error(
    `ERROR: ${OUT_PATH} is stale or hand-edited — run \`npm run db:baseline\` and commit the result.`,
  );
  process.exit(1);
}

if (current === expected) {
  console.log(`Unchanged: ${OUT_PATH}.`);
  process.exit(0);
}
writeFileSync(OUT_PATH, expected);
console.log(
  `Wrote ${OUT_PATH}. Its sha256 changed: existing databases need docs/ops/recover-from-schema-change.md.`,
);
